guestbook:
  image: guestbook
  ports:
    - 3000:3000
  links:
    - redismaster:redis-master
    - redisslave:redis-slave
redismaster:
  image: redis
  ports:
    - 3001:6379
redisslave:
  image: kubernetes/redis-slave:v2
  links:
    - redismaster:redis-master
  ports:
    - 3002:6379
